---
apiVersion: dorch.beebs.dev/v1
kind: Game
metadata:
  name: game-db650291-95fa-4f9c-a7fa-2bcaf9e48888
  namespace: dorch
spec:
  game_id: db650291-95fa-4f9c-a7fa-2bcaf9e48888
  name: "DWANGO5 DEATHMATCH"
  max_players: 64
  s3_secret_name: game-spaces-cred
  iwad: 17bdc0a8-8a81-4b00-90d1-972bf406fa10
  use_doom1_assets: false
  skill: 4
  warp: MAP02
  gamemode: Deathmatch
  dmflags: 6144 # 4096 + 2048
  frag_limit: 20
  time_limit: 7
  files:
    - 22a0ca23-f044-4319-a7a6-f3b60276d0ce
    - 15f96475-3d6c-4bd6-b37d-8d3a69b296ad
