---
apiVersion: dorch.beebs.dev/v1
kind: Game
metadata:
  name: game-cd5308d6-4eb7-4e33-8137-431b39d38d3d
  namespace: dorch
spec:
  game_id: cd5308d6-4eb7-4e33-8137-431b39d38d3d
  name: "NOSTALGIC ENTROPY"
  max_players: 64
  s3_secret_name: game-spaces-cred
  iwad: 17bdc0a8-8a81-4b00-90d1-972bf406fa10
  use_doom1_assets: false
  skill: 4
  warp: MAP01
  files:
    - 22a0ca23-f044-4319-a7a6-f3b60276d0ce
    - 0c285c8c-462a-45d8-aa60-7acd8cc1ee75
