apiVersion: v1
kind: Pod
metadata:
  name: archiver-0
  namespace: wad
spec:
  containers:
    - name: archiver-a
      image: thavlik/dorch-archiver:latest
      imagePullPolicy: Always
      command: ["python", "-u", "/app/download_wad.py"]
      env:
        - name: START_RANGE
          value: "0"
        - name: END_RANGE
          value: "16"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: secret_access_key
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 512Mi
      volumeMounts:
        - name: data
          mountPath: /data
    - name: archiver-b
      image: thavlik/dorch-archiver:latest
      imagePullPolicy: Always
      command: ["python", "-u", "/app/download_wad.py"]
      env:
        - name: START_RANGE
          value: "16"
        - name: END_RANGE
          value: "32"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: secret_access_key
    - name: archiver-c
      image: thavlik/dorch-archiver:latest
      imagePullPolicy: Always
      command: ["python", "-u", "/app/download_wad.py"]
      env:
        - name: START_RANGE
          value: "32"
        - name: END_RANGE
          value: "48"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: secret_access_key
      volumeMounts:
        - name: data
          mountPath: /data
    - name: archiver-d
      image: thavlik/dorch-archiver:latest
      imagePullPolicy: Always
      command: ["python", "-u", "/app/download_wad.py"]
      env:
        - name: START_RANGE
          value: "48"
        - name: END_RANGE
          value: "64"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: secret_access_key
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 512Mi
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data-0
---
apiVersion: v1
kind: Pod
metadata:
  name: archiver-1
  namespace: wad
spec:
  containers:
    - name: archiver-a
      image: thavlik/dorch-archiver:latest
      imagePullPolicy: Always
      command: ["python", "-u", "/app/download_wad.py"]
      env:
        - name: START_RANGE
          value: "64"
        - name: END_RANGE
          value: "80"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: secret_access_key
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 512Mi
      volumeMounts:
        - name: data
          mountPath: /data
    - name: archiver-b
      image: thavlik/dorch-archiver:latest
      imagePullPolicy: Always
      command: ["python", "-u", "/app/download_wad.py"]
      env:
        - name: START_RANGE
          value: "80"
        - name: END_RANGE
          value: "96"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: secret_access_key
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 512Mi
      volumeMounts:
        - name: data
          mountPath: /data
    - name: archiver-c
      image: thavlik/dorch-archiver:latest
      imagePullPolicy: Always
      command: ["python", "-u", "/app/download_wad.py"]
      env:
        - name: START_RANGE
          value: "96"
        - name: END_RANGE
          value: "112"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: secret_access_key
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 512Mi
      volumeMounts:
        - name: data
          mountPath: /data
    - name: archiver-d
      image: thavlik/dorch-archiver:latest
      imagePullPolicy: Always
      command: ["python", "-u", "/app/download_wad.py"]
      env:
        - name: START_RANGE
          value: "112"
        - name: END_RANGE
          value: "128"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: secret_access_key
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 512Mi
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data-1
---
apiVersion: v1
kind: Pod
metadata:
  name: archiver-2
  namespace: wad
spec:
  containers:
    - name: archiver-a
      image: thavlik/dorch-archiver:latest
      imagePullPolicy: Always
      command: ["python", "-u", "/app/download_wad.py"]
      env:
        - name: START_RANGE
          value: "128"
        - name: END_RANGE
          value: "144"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: secret_access_key
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 512Mi
      volumeMounts:
        - name: data
          mountPath: /data
    - name: archiver-b
      image: thavlik/dorch-archiver:latest
      imagePullPolicy: Always
      command: ["python", "-u", "/app/download_wad.py"]
      env:
        - name: START_RANGE
          value: "144"
        - name: END_RANGE
          value: "160"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: secret_access_key
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 512Mi
      volumeMounts:
        - name: data
          mountPath: /data
    - name: archiver-c
      image: thavlik/dorch-archiver:latest
      imagePullPolicy: Always
      command: ["python", "-u", "/app/download_wad.py"]
      env:
        - name: START_RANGE
          value: "160"
        - name: END_RANGE
          value: "176"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: secret_access_key
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 512Mi
      volumeMounts:
        - name: data
          mountPath: /data
    - name: archiver-d
      image: thavlik/dorch-archiver:latest
      imagePullPolicy: Always
      command: ["python", "-u", "/app/download_wad.py"]
      env:
        - name: START_RANGE
          value: "176"
        - name: END_RANGE
          value: "192"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: secret_access_key
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 512Mi
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data-2
---
apiVersion: v1
kind: Pod
metadata:
  name: archiver-3
  namespace: wad
spec:
  containers:
    - name: archiver-a
      image: thavlik/dorch-archiver:latest
      imagePullPolicy: Always
      command: ["python", "-u", "/app/download_wad.py"]
      env:
        - name: START_RANGE
          value: "192"
        - name: END_RANGE
          value: "208"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: secret_access_key
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 512Mi
      volumeMounts:
        - name: data
          mountPath: /data
    - name: archiver-b
      image: thavlik/dorch-archiver:latest
      imagePullPolicy: Always
      command: ["python", "-u", "/app/download_wad.py"]
      env:
        - name: START_RANGE
          value: "208"
        - name: END_RANGE
          value: "224"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: secret_access_key
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 512Mi
      volumeMounts:
        - name: data
          mountPath: /data
    - name: archiver-c
      image: thavlik/dorch-archiver:latest
      imagePullPolicy: Always
      command: ["python", "-u", "/app/download_wad.py"]
      env:
        - name: START_RANGE
          value: "224"
        - name: END_RANGE
          value: "240"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: secret_access_key
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 512Mi
      volumeMounts:
        - name: data
          mountPath: /data
    - name: archiver-d
      image: thavlik/dorch-archiver:latest
      imagePullPolicy: Always
      command: ["python", "-u", "/app/download_wad.py"]
      env:
        - name: START_RANGE
          value: "240"
        - name: END_RANGE
          value: "256"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: secret_access_key
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 512Mi
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data-3
