apiVersion: v1
kind: Pod
metadata:
  name: meta
  namespace: wad
spec:
  containers:
    - name: meta
      image: thavlik/dorch-archiver:latest
      imagePullPolicy: Always
      command:
        - python
        - -u
        - /app/meta.py
        - --pretty
        - --wads-json
        - https://wadarchive.nyc3.digitaloceanspaces.com/wads.json
        - --idgames-json
        - https://wadarchive.nyc3.digitaloceanspaces.com/idgames.json
        - --post-to-wadinfo
        - --wadinfo-base-url
        - http://dorch-wadinfo.dorch.svc.cluster.local
        - --images-bucket
        - wadimages
      env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: secret_access_key
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 2000m
          memory: 1024Mi