apiVersion: v1
kind: Pod
metadata:
  name: meta-dispatch
  namespace: dorch
spec:
  restartPolicy: Never
  containers:
    - name: meta
      image: thavlik/dorch-archiver:latest
      imagePullPolicy: Always
      command:
        - python
        - -u
        - /app/meta-dispatch.py
        #- --start
        #- "0"
        - --limit
        - "10"
        - --readmes-json
        - https://wadarchive2.nyc3.digitaloceanspaces.com/readmes.json
        - --wads-json
        - https://wadarchive2.nyc3.digitaloceanspaces.com/wads.json
        - --idgames-json
        - https://wadarchive2.nyc3.digitaloceanspaces.com/idgames.json
      env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: NATS_URL
          value: "nats://nats.nats.svc.cluster.local:4222"
        - name: NATS_USER
          valueFrom:
            secretKeyRef:
              name: nats-cred
              key: user
        - name: NATS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nats-cred
              key: password
      resources:
        requests:
          cpu: 500m
          memory: 512Mi