apiVersion: dorch.beebs.dev/v1
kind: Game
metadata:
  name: test-game
  namespace: dorch
spec:
  game_id: 25464d97-353d-4584-bc16-e72346f92d6f
  name: "MyTestGame"
  max_players: 64
  s3_secret_name: s3-cred
  iwad: freedoom2.wad
  use_doom1_assets: true
  files:
    - sunlust.wad
  #debug_udp: true
